const PROJECTS_DATA = {
    "house-for-trees": {
        "title": "House for Trees",
        "titleVi": "Nhà cho Cây",
        "location": "Quận Tân Bình, TP. Hồ Chí Minh",
        "locationFull": "Quận Tân Bình, TP. Hồ Chí Minh",
        "locationEn": "Tan Binh District, Ho Chi Minh City, Vietnam",
        "locationFullEn": "Tan Binh District, Ho Chi Minh City, Vietnam",
        "year": "04/2014",
        "awards": [
            "🏆 Giải thưởng AR House — Giải Nhất",
            "🏆 World Architecture Festival — Chiến thắng",
            "🏆 FuturArc Green Leadership Award — Chiến thắng",
            "🏆 Green Good Design Award — Chiến thắng",
            "🏆 International Architecture Award — Chiến thắng",
            "🏆 ARCASIA Award — Danh dự",
            "🏆 A' Design Award — Giải Bạc"
        ],
        "awardsEn": [
            "🏆 AR House Award — Winner",
            "🏆 World Architecture Festival — Winner",
            "🏆 FuturArc Green Leadership Award — Winner",
            "🏆 Green Good Design Award — Winner",
            "🏆 International Architecture Award — Winner",
            "🏆 ARCASIA Award — Honorary",
            "🏆 A' Design Award — Silver"
        ],
        "description": "Nhà cho Cây được xây dựng trên một lô đất trống thuộc Quận Tân Bình, TP. Hồ Chí Minh — nơi có mật độ dân cư đông đúc với những ngôi nhà nhỏ chen chúc nhau. Dựa trên ý tưởng những “chậu cây”, công trình được chia thành 5 khối có thể trồng cây xanh trên mái; khoảng trống giữa các khối được tận dụng làm các khu vườn nhỏ.",
        "descriptionEn": "House for Trees is built on a vacant lot in Tan Binh District, Ho Chi Minh City, where small houses are densely packed. Inspired by “tree planters”, the project is composed of five volumes that host rooftop trees, with the spaces between them forming small gardens.",
        "image": "projects/Green/House%20for%20Trees/1.jpg",
        "gallery": [
            "projects/Green/House%20for%20Trees/1.jpg",
            "projects/Green/House%20for%20Trees/2.jpg",
            "projects/Green/House%20for%20Trees/3.jpg",
            "projects/Green/House%20for%20Trees/4.jpg",
            "projects/Green/House%20for%20Trees/5.jpg",
            "projects/Green/House%20for%20Trees/5.1.jpg",
            "projects/Green/House%20for%20Trees/6.jpg",
            "projects/Green/House%20for%20Trees/7.jpg",
            "projects/Green/House%20for%20Trees/8.jpg",
            "projects/Green/House%20for%20Trees/9.jpg",
            "projects/Green/House%20for%20Trees/10.jpg",
            "projects/Green/House%20for%20Trees/11.jpg"
        ],
        "category": "green"
    },
    "stacking-green": {
        "title": "Stacking Green",
        "titleVi": "Stacking Green",
        "location": "TP. Hồ Chí Minh",
        "locationFull": "TP. Hồ Chí Minh, Việt Nam",
        "locationEn": "Ho Chi Minh City, Vietnam",
        "locationFullEn": "Ho Chi Minh City, Vietnam",
        "year": "02/2011",
        "awards": [
            "🏆 FuturArc Green Leadership Award",
            "🏆 Green Good Design Award",
            "🏆 International Architecture Award",
            "🏆 World Architecture Festival",
            "🏆 ARCASIA Award — Danh dự",
            "🏆 ArchDaily Building of the Year 2012"
        ],
        "awardsEn": [
            "🏆 FuturArc Green Leadership Award",
            "🏆 Green Good Design Award",
            "🏆 International Architecture Award",
            "🏆 World Architecture Festival",
            "🏆 ARCASIA Award — Honorary",
            "🏆 ArchDaily Building of the Year 2012"
        ],
        "description": "Stacking Green là một thử nghiệm “xanh hoá” nhà ống tại TP. Hồ Chí Minh. Mặt tiền gồm các bồn cây trên hệ lam giúp che nắng, thông gió tự nhiên và đưa mảng xanh trở lại khu phố.",
        "descriptionEn": "Stacking Green is an experiment to “green” the typical Vietnamese tube house in Ho Chi Minh City. Planter boxes integrated into the façade louvers provide shading, natural ventilation, and a stronger presence of greenery in the neighborhood.",
        "image": "projects/Green/Stacking%20Green/1.jpg",
        "gallery": [
            "projects/Green/Stacking%20Green/1.jpg",
            "projects/Green/Stacking%20Green/2.jpg",
            "projects/Green/Stacking%20Green/3.jpg",
            "projects/Green/Stacking%20Green/4.jpg",
            "projects/Green/Stacking%20Green/5.jpg",
            "projects/Green/Stacking%20Green/6.jpg",
            "projects/Green/Stacking%20Green/7.jpg",
            "projects/Green/Stacking%20Green/8.jpg",
            "projects/Green/Stacking%20Green/9.jpg",
            "projects/Green/Stacking%20Green/10.jpg",
            "projects/Green/Stacking%20Green/11.jpg",
            "projects/Green/Stacking%20Green/12.jpg",
            "projects/Green/Stacking%20Green/13.jpg",
            "projects/Green/Stacking%20Green/14.jpg",
            "projects/Green/Stacking%20Green/15.jpg",
            "projects/Green/Stacking%20Green/16.jpg",
            "projects/Green/Stacking%20Green/17.jpg",
            "projects/Green/Stacking%20Green/18.jpg",
            "projects/Green/Stacking%20Green/19.jpg",
            "projects/Green/Stacking%20Green/20.jpg"
        ],
        "category": "green"
    },
    "ha-long-villa": {
        "title": "Ha Long Villa",
        "titleVi": "Biệt thự Hạ Long",
        "location": "Hạ Long, Việt Nam",
        "locationFull": "Hạ Long, Quảng Ninh, Việt Nam",
        "locationEn": "Ha Long, Vietnam",
        "locationFullEn": "Ha Long, Quang Ninh, Vietnam",
        "year": "04/2020",
        "awards": [],
        "awardsEn": [],
        "description": "Biệt thự Hạ Long nằm gần bờ biển và hướng tầm nhìn ra Vịnh Hạ Long. Công trình hướng đến sự hài hoà với cảnh quan xung quanh, ưu tiên ánh sáng tự nhiên, thông gió và những khoảng xanh đệm.",
        "descriptionEn": "Ha Long Villa sits close to the coastline with views toward Ha Long Bay. The design aims to blend with its surroundings, prioritizing natural light, cross-ventilation, and green buffer spaces.",
        "image": "projects/Green/Ha%20Long%20Villa/1.jpg",
        "gallery": [
            "projects/Green/Ha%20Long%20Villa/1.jpg",
            "projects/Green/Ha%20Long%20Villa/2.jpg",
            "projects/Green/Ha%20Long%20Villa/3.jpg",
            "projects/Green/Ha%20Long%20Villa/4.jpg",
            "projects/Green/Ha%20Long%20Villa/5.jpg",
            "projects/Green/Ha%20Long%20Villa/6.jpg",
            "projects/Green/Ha%20Long%20Villa/7.jpg",
            "projects/Green/Ha%20Long%20Villa/8.jpg",
            "projects/Green/Ha%20Long%20Villa/9.jpg",
            "projects/Green/Ha%20Long%20Villa/10.jpg",
            "projects/Green/Ha%20Long%20Villa/11.jpg",
            "projects/Green/Ha%20Long%20Villa/12.jpg",
            "projects/Green/Ha%20Long%20Villa/13.jpg",
            "projects/Green/Ha%20Long%20Villa/14.jpg",
            "projects/Green/Ha%20Long%20Villa/15.jpg",
            "projects/Green/Ha%20Long%20Villa/16.jpg",
            "projects/Green/Ha%20Long%20Villa/17.jpg",
            "projects/Green/Ha%20Long%20Villa/18.jpg",
            "projects/Green/Ha%20Long%20Villa/19.jpg",
            "projects/Green/Ha%20Long%20Villa/20.jpg",
            "projects/Green/Ha%20Long%20Villa/21.jpg",
            "projects/Green/Ha%20Long%20Villa/22.jpg"
        ],
        "category": "green"
    },
    "vtn-office": {
        "title": "VTN Office",
        "titleVi": "Văn phòng VTN",
        "location": "TP. Thủ Đức, TP. Hồ Chí Minh",
        "locationFull": "TP. Thủ Đức, TP. Hồ Chí Minh, Việt Nam",
        "locationEn": "Thu Duc City, Ho Chi Minh City, Vietnam",
        "locationFullEn": "Thu Duc City, Ho Chi Minh City, Vietnam",
        "year": "08/2022",
        "awards": [],
        "awardsEn": [],
        "description": "Urban Farming Office là nỗ lực đưa mảng xanh và “nông nghiệp đô thị” trở lại không gian làm việc. Mặt tiền sử dụng các hộp trồng cây treo, tạo lớp đệm vi khí hậu và tăng kết nối với thiên nhiên.",
        "descriptionEn": "The Urban Farming Office brings greenery and “urban farming” into the workplace. Hanging planters on the façade form a microclimate buffer while strengthening the connection to nature.",
        "image": "projects/Green/VTN%20Office/1.jpg",
        "gallery": [
            "projects/Green/VTN%20Office/1.jpg",
            "projects/Green/VTN%20Office/2.jpg",
            "projects/Green/VTN%20Office/3.jpg",
            "projects/Green/VTN%20Office/4.jpg",
            "projects/Green/VTN%20Office/5.jpg",
            "projects/Green/VTN%20Office/6.jpg",
            "projects/Green/VTN%20Office/7.jpg",
            "projects/Green/VTN%20Office/8.jpg",
            "projects/Green/VTN%20Office/9.jpg",
            "projects/Green/VTN%20Office/10.jpg",
            "projects/Green/VTN%20Office/11.jpg",
            "projects/Green/VTN%20Office/12.jpg",
            "projects/Green/VTN%20Office/13.jpg",
            "projects/Green/VTN%20Office/14.jpg",
            "projects/Green/VTN%20Office/15.jpg",
            "projects/Green/VTN%20Office/16.jpg",
            "projects/Green/VTN%20Office/17.jpg",
            "projects/Green/VTN%20Office/18.jpg",
            "projects/Green/VTN%20Office/19.jpg",
            "projects/Green/VTN%20Office/20.jpg"
        ],
        "category": "green"
    },
    "bamboo-wing": {
        "title": "Bamboo Wing",
        "titleVi": "Cánh Tre",
        "location": "Vĩnh Phúc, Việt Nam",
        "locationFull": "Đại Lải, Vĩnh Phúc, Việt Nam",
        "locationEn": "Vinh Phuc, Vietnam",
        "locationFullEn": "Dai Lai, Vinh Phuc, Vietnam",
        "year": "07/2009",
        "awards": [
            "🏆 Green Good Design Award",
            "🏆 International Architecture Award",
            "🏆 FuturArc Green Leadership Award",
            "🏆 Vietnam Green Architecture Award"
        ],
        "awardsEn": [
            "🏆 Green Good Design Award",
            "🏆 International Architecture Award",
            "🏆 FuturArc Green Leadership Award",
            "🏆 Vietnam Green Architecture Award"
        ],
        "description": "Được bao quanh bởi thiên nhiên gần Hà Nội, Bamboo Wing là cấu trúc đúc bằng tre bay trên bầu trời như những cánh chim. Kết cấu rộng 12m tự cân bằng trên một chân, tạo không gian trống rộng mà không cần cột ở rìa.",
        "descriptionEn": "Surrounded by nature near Hanoi, Bamboo Wing is a bamboo structure that seems to glide like a bird’s wings. The 12m-wide structure balances on a single support, creating a large column-free space along its edges.",
        "image": "projects/Bamboo/Bamboo%20Wing/1.jpg",
        "gallery": [
            "projects/Bamboo/Bamboo%20Wing/1.jpg",
            "projects/Bamboo/Bamboo%20Wing/2.jpg",
            "projects/Bamboo/Bamboo%20Wing/3.jpg",
            "projects/Bamboo/Bamboo%20Wing/4.jpg",
            "projects/Bamboo/Bamboo%20Wing/5.jpg",
            "projects/Bamboo/Bamboo%20Wing/6.jpg",
            "projects/Bamboo/Bamboo%20Wing/7.jpg",
            "projects/Bamboo/Bamboo%20Wing/8.jpg",
            "projects/Bamboo/Bamboo%20Wing/9.jpg",
            "projects/Bamboo/Bamboo%20Wing/10.jpg",
            "projects/Bamboo/Bamboo%20Wing/11.jpg",
            "projects/Bamboo/Bamboo%20Wing/12.jpg",
            "projects/Bamboo/Bamboo%20Wing/13.jpg",
            "projects/Bamboo/Bamboo%20Wing/14.jpg",
            "projects/Bamboo/Bamboo%20Wing/15.jpg"
        ],
        "category": "bamboo"
    },
    "kontum-indochine": {
        "title": "Kontum Indochine",
        "titleVi": "Kontum Indochine",
        "location": "Kon Tum, Việt Nam",
        "locationFull": "TP. Kon Tum, Việt Nam",
        "locationEn": "Kon Tum, Vietnam",
        "locationFullEn": "Kon Tum City, Vietnam",
        "year": "01/2013",
        "awards": [
            "🏆 World Architecture Festival",
            "🏆 Green Good Design Award",
            "🏆 FuturArc Green Leadership Award"
        ],
        "awardsEn": [
            "🏆 World Architecture Festival",
            "🏆 Green Good Design Award",
            "🏆 FuturArc Green Leadership Award"
        ],
        "description": "Kontum Indochine sử dụng tre và vật liệu địa phương để tạo không gian lưu trú – sinh hoạt gần gũi thiên nhiên. Hệ kết cấu và thông gió tự nhiên giúp giảm phụ thuộc điều hoà, phù hợp khí hậu nhiệt đới.",
        "descriptionEn": "Kontum Indochine uses bamboo and local materials to create an accommodation and communal space connected to nature. Its structure and natural ventilation reduce reliance on air-conditioning in a tropical climate.",
        "image": "projects/Bamboo/Kontum%20Indochine/1.jpg",
        "gallery": [
            "projects/Bamboo/Kontum%20Indochine/1.jpg",
            "projects/Bamboo/Kontum%20Indochine/2.jpg",
            "projects/Bamboo/Kontum%20Indochine/3.jpg",
            "projects/Bamboo/Kontum%20Indochine/4.jpg",
            "projects/Bamboo/Kontum%20Indochine/5.jpg",
            "projects/Bamboo/Kontum%20Indochine/6.jpg",
            "projects/Bamboo/Kontum%20Indochine/7.jpg",
            "projects/Bamboo/Kontum%20Indochine/8.jpg",
            "projects/Bamboo/Kontum%20Indochine/9.jpg",
            "projects/Bamboo/Kontum%20Indochine/10.jpg",
            "projects/Bamboo/Kontum%20Indochine/11.jpg",
            "projects/Bamboo/Kontum%20Indochine/12.jpg",
            "projects/Bamboo/Kontum%20Indochine/13.jpg",
            "projects/Bamboo/Kontum%20Indochine/14.jpg",
            "projects/Bamboo/Kontum%20Indochine/15.jpg",
            "projects/Bamboo/Kontum%20Indochine/16.jpg",
            "projects/Bamboo/Kontum%20Indochine/17.jpg",
            "projects/Bamboo/Kontum%20Indochine/18.jpg",
            "projects/Bamboo/Kontum%20Indochine/19.jpg",
            "projects/Bamboo/Kontum%20Indochine/20.jpg"
        ],
        "category": "bamboo"
    },
    "son-la-restaurant": {
        "title": "Son La Restaurant",
        "titleVi": "Nhà hàng Sơn La",
        "location": "Sơn La, Việt Nam",
        "locationFull": "Sơn La, Việt Nam",
        "locationEn": "Son La, Vietnam",
        "locationFullEn": "Son La, Vietnam",
        "year": "01/2014",
        "awards": [
            "🏆 FuturArc Green Leadership Award",
            "🏆 Green Good Design Award"
        ],
        "awardsEn": [
            "🏆 FuturArc Green Leadership Award",
            "🏆 Green Good Design Award"
        ],
        "description": "Nhà hàng Sơn La khai thác tre và vật liệu địa phương để tạo không gian ăn uống thoáng mát. Mái và kết cấu giúp che nắng, đón gió, mang lại trải nghiệm gần gũi với khí hậu và cảnh quan vùng Tây Bắc.",
        "descriptionEn": "Son La Restaurant uses bamboo and local materials to create an airy dining space. The roof and structure provide shading and airflow, offering a comfortable experience aligned with the climate and landscape of Vietnam’s Northwest.",
        "image": "projects/Bamboo/Son%20La%20Restaurant/1.jpg",
        "gallery": [
            "projects/Bamboo/Son%20La%20Restaurant/1.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/2.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/3.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/4.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/5.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/6.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/7.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/8.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/9.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/10.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/11.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/12.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/13.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/14.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/15.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/16.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/17.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/18.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/19.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/20.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/21.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/22.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/23.jpg",
            "projects/Bamboo/Son%20La%20Restaurant/24.jpg"
        ],
        "category": "bamboo"
    },
    "vedana-resort": {
        "title": "Vedana Resort",
        "titleVi": "Khu nghỉ dưỡng Vedana",
        "location": "Ninh Bình, Việt Nam",
        "locationFull": "Ninh Bình, Việt Nam",
        "locationEn": "Ninh Binh, Vietnam",
        "locationFullEn": "Ninh Binh, Vietnam",
        "year": "10/2020",
        "awards": [],
        "awardsEn": [],
        "description": "Vedana Resort nằm giữa cảnh quan núi đá vôi và mặt nước đặc trưng của Ninh Bình. Thiết kế ưu tiên vật liệu tự nhiên, những không gian mở và hệ mái che giúp công trình gần gũi với thiên nhiên.",
        "descriptionEn": "Vedana Resort sits within Ninh Binh’s distinctive limestone and water landscape. The design favors natural materials, open spaces, and shading roofs to keep the architecture closely connected to its setting.",
        "image": "projects/Bamboo/Vedana%20Resort/1.jpg",
        "gallery": [
            "projects/Bamboo/Vedana%20Resort/1.jpg",
            "projects/Bamboo/Vedana%20Resort/2.jpg",
            "projects/Bamboo/Vedana%20Resort/3.jpg",
            "projects/Bamboo/Vedana%20Resort/4.jpg",
            "projects/Bamboo/Vedana%20Resort/5.jpg",
            "projects/Bamboo/Vedana%20Resort/6.jpg",
            "projects/Bamboo/Vedana%20Resort/7.jpg",
            "projects/Bamboo/Vedana%20Resort/8.jpg",
            "projects/Bamboo/Vedana%20Resort/9.jpg",
            "projects/Bamboo/Vedana%20Resort/10.jpg",
            "projects/Bamboo/Vedana%20Resort/11.jpg",
            "projects/Bamboo/Vedana%20Resort/12.jpg",
            "projects/Bamboo/Vedana%20Resort/13.jpg",
            "projects/Bamboo/Vedana%20Resort/14.jpg",
            "projects/Bamboo/Vedana%20Resort/15.jpg",
            "projects/Bamboo/Vedana%20Resort/16.jpg",
            "projects/Bamboo/Vedana%20Resort/17.jpg",
            "projects/Bamboo/Vedana%20Resort/18.jpg",
            "projects/Bamboo/Vedana%20Resort/19.jpg"
        ],
        "category": "bamboo"
    },

    // ============================================
    // DEMO PROJECTS (Duplicates for grid testing)
    // ============================================
    "s-house": {
        "title": "S House",
        "titleVi": "Nhà S",
        "location": "Biên Hòa, Việt Nam",
        "locationFull": "Biên Hòa, Đồng Nai, Việt Nam",
        "locationEn": "Bien Hoa, Vietnam",
        "locationFullEn": "Bien Hoa, Dong Nai, Vietnam",
        "year": "03/2015",
        "awards": ["🏆 Green Good Design Award"],
        "awardsEn": ["🏆 Green Good Design Award"],
        "description": "S House là một ngôi nhà kết hợp giữa không gian sống và cây xanh.",
        "descriptionEn": "S House combines living space with green plants.",
        "image": "projects/Green/House%20for%20Trees/2.jpg",
        "gallery": ["projects/Green/House%20for%20Trees/2.jpg"],
        "category": "green"
    },
    "binh-house": {
        "title": "Binh House",
        "titleVi": "Nhà Bình",
        "location": "TP. Hồ Chí Minh",
        "locationFull": "TP. Hồ Chí Minh, Việt Nam",
        "locationEn": "Ho Chi Minh City, Vietnam",
        "locationFullEn": "Ho Chi Minh City, Vietnam",
        "year": "09/2016",
        "awards": ["🏆 World Architecture Festival"],
        "awardsEn": ["🏆 World Architecture Festival"],
        "description": "Binh House là một nơi trú ẩn yên tĩnh.",
        "descriptionEn": "Binh House is a peaceful retreat.",
        "image": "projects/Green/Stacking%20Green/5.jpg",
        "gallery": ["projects/Green/Stacking%20Green/5.jpg"],
        "category": "green"
    },
    "thao-dien-house": {
        "title": "Thao Dien House",
        "titleVi": "Nhà Thảo Điền",
        "location": "Quận 2, TP. Hồ Chí Minh",
        "locationFull": "Thảo Điền, Quận 2, TP. Hồ Chí Minh",
        "locationEn": "District 2, Ho Chi Minh City",
        "locationFullEn": "Thao Dien, District 2, Ho Chi Minh City",
        "year": "06/2019",
        "awards": [],
        "awardsEn": [],
        "description": "Thao Dien House sử dụng thiết kế nhiều tầng xanh.",
        "descriptionEn": "Thao Dien House employs multi-level green design.",
        "image": "projects/Green/Ha%20Long%20Villa/3.jpg",
        "gallery": ["projects/Green/Ha%20Long%20Villa/3.jpg"],
        "category": "green"
    },
    "green-renovation": {
        "title": "Green Renovation",
        "titleVi": "Cải tạo Xanh",
        "location": "Đà Nẵng, Việt Nam",
        "locationFull": "Đà Nẵng, Việt Nam",
        "locationEn": "Da Nang, Vietnam",
        "locationFullEn": "Da Nang, Vietnam",
        "year": "02/2021",
        "awards": [],
        "awardsEn": [],
        "description": "Green Renovation là dự án cải tạo xanh.",
        "descriptionEn": "Green Renovation is a green renovation project.",
        "image": "projects/Green/VTN%20Office/5.jpg",
        "gallery": ["projects/Green/VTN%20Office/5.jpg"],
        "category": "green"
    },
    "dai-lai-bamboo": {
        "title": "Dai Lai Bamboo",
        "titleVi": "Tre Đại Lải",
        "location": "Đại Lải, Việt Nam",
        "locationFull": "Đại Lải, Vĩnh Phúc, Việt Nam",
        "locationEn": "Dai Lai, Vietnam",
        "locationFullEn": "Dai Lai, Vinh Phuc, Vietnam",
        "year": "08/2011",
        "awards": ["🏆 FuturArc Green Leadership Award"],
        "awardsEn": ["🏆 FuturArc Green Leadership Award"],
        "description": "Dai Lai Bamboo là một công trình tre độc đáo.",
        "descriptionEn": "Dai Lai Bamboo is a unique bamboo structure.",
        "image": "projects/Bamboo/Bamboo%20Wing/3.jpg",
        "gallery": ["projects/Bamboo/Bamboo%20Wing/3.jpg"],
        "category": "bamboo"
    },
    "binh-duong-school": {
        "title": "Binh Duong School",
        "titleVi": "Trường Bình Dương",
        "location": "Bình Dương, Việt Nam",
        "locationFull": "Bình Dương, Việt Nam",
        "locationEn": "Binh Duong, Vietnam",
        "locationFullEn": "Binh Duong, Vietnam",
        "year": "01/2017",
        "awards": [],
        "awardsEn": [],
        "description": "Binh Duong School là dự án thiết kế trường học.",
        "descriptionEn": "Binh Duong School is an educational facility.",
        "image": "projects/Bamboo/Kontum%20Indochine/5.jpg",
        "gallery": ["projects/Bamboo/Kontum%20Indochine/5.jpg"],
        "category": "bamboo"
    },
    "nocenco-cafe": {
        "title": "Nocenco Cafe",
        "titleVi": "Quán Cà Phê Nocenco",
        "location": "Vinh, Việt Nam",
        "locationFull": "Vinh, Nghệ An, Việt Nam",
        "locationEn": "Vinh, Vietnam",
        "locationFullEn": "Vinh, Nghe An, Vietnam",
        "year": "05/2018",
        "awards": ["🏆 ArchDaily Building of the Year"],
        "awardsEn": ["🏆 ArchDaily Building of the Year"],
        "description": "Nocenco Cafe là một quán cà phê với thiết kế tre độc đáo.",
        "descriptionEn": "Nocenco Cafe is a unique bamboo-designed coffee shop.",
        "image": "projects/Bamboo/Son%20La%20Restaurant/4.jpg",
        "gallery": ["projects/Bamboo/Son%20La%20Restaurant/4.jpg"],
        "category": "bamboo"
    },
    "bamboo-pavilion": {
        "title": "Bamboo Pavilion",
        "titleVi": "Gian Tre",
        "location": "Milano, Italy",
        "locationFull": "Milan, Italy",
        "locationEn": "Milan, Italy",
        "locationFullEn": "Milan, Italy",
        "year": "05/2015",
        "awards": ["🏆 World Expo 2015"],
        "awardsEn": ["🏆 World Expo 2015"],
        "description": "Bamboo Pavilion là công trình biểu tượng tại World Expo 2015.",
        "descriptionEn": "Bamboo Pavilion is an iconic structure at World Expo 2015.",
        "image": "projects/Bamboo/Vedana%20Resort/5.jpg",
        "gallery": ["projects/Bamboo/Vedana%20Resort/5.jpg"],
        "category": "bamboo"
    },
    "wind-and-water-bar": {
        "title": "Wind and Water Bar",
        "titleVi": "Quán Gió Nước",
        "location": "Thủ Đức, TP. Hồ Chí Minh",
        "locationFull": "Thủ Đức, TP. Hồ Chí Minh",
        "locationEn": "Thu Duc, Ho Chi Minh City",
        "locationFullEn": "Thu Duc, Ho Chi Minh City",
        "year": "07/2008",
        "awards": ["🏆 Green Good Design Award"],
        "awardsEn": ["🏆 Green Good Design Award"],
        "description": "Wind and Water Bar là một quán bar tre giữa hồ nước.",
        "descriptionEn": "Wind and Water Bar is a bamboo bar over water.",
        "image": "projects/Bamboo/Bamboo%20Wing/8.jpg",
        "gallery": ["projects/Bamboo/Bamboo%20Wing/8.jpg"],
        "category": "bamboo"
    },
    "a-house": {
        "title": "A House",
        "titleVi": "Nhà A",
        "location": "Đà Lạt, Việt Nam",
        "locationFull": "Đà Lạt, Lâm Đồng, Việt Nam",
        "locationEn": "Da Lat, Vietnam",
        "locationFullEn": "Da Lat, Lam Dong, Vietnam",
        "year": "12/2019",
        "awards": [],
        "awardsEn": [],
        "description": "A House là một ngôi nhà nghỉ dưỡng ẩn mình trong rừng thông.",
        "descriptionEn": "A House is a retreat hidden in pine forests.",
        "image": "projects/Green/Ha%20Long%20Villa/10.jpg",
        "gallery": ["projects/Green/Ha%20Long%20Villa/10.jpg"],
        "category": "green"
    },
    "farming-kindergarten": {
        "title": "Farming Kindergarten",
        "titleVi": "Trường Mầm Non Nông Trại",
        "location": "Đồng Nai, Việt Nam",
        "locationFull": "Biên Hòa, Đồng Nai, Việt Nam",
        "locationEn": "Dong Nai, Vietnam",
        "locationFullEn": "Bien Hoa, Dong Nai, Vietnam",
        "year": "12/2013",
        "awards": ["🏆 ArchDaily Building of the Year 2015"],
        "awardsEn": ["🏆 ArchDaily Building of the Year 2015"],
        "description": "Farming Kindergarten là trường mầm non với mái xanh.",
        "descriptionEn": "Farming Kindergarten is a preschool with a vegetable garden roof.",
        "image": "projects/Green/House%20for%20Trees/7.jpg",
        "gallery": ["projects/Green/House%20for%20Trees/7.jpg"],
        "category": "green"
    },
    "naman-spa": {
        "title": "Naman Spa",
        "titleVi": "Naman Spa",
        "location": "Đà Nẵng, Việt Nam",
        "locationFull": "Đà Nẵng, Việt Nam",
        "locationEn": "Da Nang, Vietnam",
        "locationFullEn": "Da Nang, Vietnam",
        "year": "06/2015",
        "awards": ["🏆 FuturArc Green Leadership Award"],
        "awardsEn": ["🏆 FuturArc Green Leadership Award"],
        "description": "Naman Spa sử dụng tre để tạo không gian thư giãn.",
        "descriptionEn": "Naman Spa uses bamboo to create a peaceful relaxation space.",
        "image": "projects/Bamboo/Kontum%20Indochine/10.jpg",
        "gallery": ["projects/Bamboo/Kontum%20Indochine/10.jpg"],
        "category": "bamboo"
    }
};


